version: '3.4'

services: 
  frontend:
    image: dotawinfrontend
    build:
      context: .
      dockerfile: Dotawin.Client/Dockerfile
    environment: 
      - backendUrl=http://backend
      - isContainer=1
    ports:
      - "5902:80"
    depends_on: 
      - backend
  backend:
    image: dotawinbackend
    build:
      context: .
      dockerfile: Dotawin.Server/Dockerfile
    environment:
      - isContainer=1
    ports: 
      - "5000:80"
  updater:
   image: dotawinupdater
   build:
     context: .
     dockerfile: Dotawin.Updater/Dockerfile
   environment:
     - backendUrl=http://backend
     - isContainer=1
   depends_on: 
     - backend